#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Cody White's Blog
url: 'https://codywhite.me'
baseurl: '' #change it according to your repository name
description: A place to collect all of my work plus more.
favicon: true ##Generate and upload files to root - https://favicon.io/favicon-converter/
fluid_icon: 'https://avatars3.githubusercontent.com/u/56890437?s=96&v=4'
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

## Thumbnail Information
google_meta: true
twitter_meta: true
facebook_meta: true
thumbnail_image: '/assets/images/meta_banner.png'
twitter_card: Summary
twitter_id: '@CodyWhite_'
og_type: Blog

# Tracker
analytics: UA-12472657-6
site_verification: #'D-vB14YLMSBSGaEeAo5uWp2g_E850BgRYnnkiV00bw4'



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"

compress_html: # - http://jch.penibelst.de/
  clippings: all
  comments: #["<!-- ", " -->"]
  endings: all
  ignore:
    envs: development
  blanklines: true
  profile: false
  #startings: [html, head, body]

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
